package j20_예외처리;

public class ExceptionTest1 {
	
	public static void main(String[] args) {
		
		int[] numArray = new int[] {1, 2, 3, 4, 5};
		
		for(int i = 0; i < 5; i++) {
			System.out.println(numArray[i]);
		}
		
		for(int i = 0; i < 6; i++) {
			
			try {
				System.out.println(numArray[i]);
			} catch (Exception e) {
				System.out.println("예외가 발생하였습니다.");
			}
			
		}
		
	}

}
